name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-readme:
    name: Update Readme with Wakatime Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKA_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_SECRET_WAKA }}
          SHOW_PROJECTS: "False"
          SHOW_LOC_CHART: "False"
